
reportBucket: 'lighthouse-checker-reports' # Name of the bucket to upload Lighthouse checks to

chrome:
  flags:
    - --headless
    - --ignore-certificate-errors
  functions:
    - lighthouse # Only inject chrome on the lighthouse funtion